env:
  es2021: true
  node: true
  jest: true

extends:
  - airbnb-base
  - plugin:jest/recommended
  - plugin:fp/recommended

plugins:
  - jest
  - fp

rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle:
    - error
    - allow:
        - __dirname
        - __filename
  fp/no-unused-expression: off
  fp/no-nil: off
  fp/no-throw: off
  fp/no-mutating-methods: off

parserOptions:
  ecmaVersion: 2021
  sourceType: module
